# Generated by Django 3.2.5 on 2022-06-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0008_roomchat_roomidapi_alter_roomchat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinnguoidung',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='', max_length=1),
        ),
    ]
